<#
.SYNOPSIS
    Extracts the collection API base URL and key from the Unity source into a
    gitignored src-tauri/.env -- without ever printing the secret.

.DESCRIPTION
    The Unity build hardcodes the API key in
    `Assets/Games/Sliding-Puzzle/Scripts/API/API.cs`. The port must not repeat
    that: the key lives in src-tauri/.env (gitignored), is read only by the Rust
    side, and is never handed to the renderer (docs/game-logic.md section 8.1).

    This script only moves the values. It prints names and character counts,
    never contents, so the transcript/CI log stays clean.

    IMPORTANT: the key in the Unity repo is committed to git history and must be
    treated as compromised. Rotate it server-side; this script will then need to
    be re-run (or the .env edited) with the new value.

    Existing values in src-tauri/.env are preserved unless -Force is passed.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File scripts/extract-api-config.ps1
#>

[CmdletBinding()]
param(
    [string] $UnityRoot = 'D:/Chitrang_ViitorCloud/R&D/Sliding-Puzzle',
    [string] $OutFile   = '',
    [switch] $Force
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($OutFile)) {
    $OutFile = Join-Path $repoRoot 'src-tauri/.env'
}

$apiFile = Join-Path $UnityRoot 'Assets/Games/Sliding-Puzzle/Scripts/API/API.cs'
if (-not (Test-Path -LiteralPath $apiFile)) {
    throw "Not found: $apiFile"
}

if ((Test-Path -LiteralPath $OutFile) -and -not $Force) {
    Write-Host "$OutFile already exists -- leaving it alone. Pass -Force to overwrite." -ForegroundColor Yellow
    exit 0
}

$source = Get-Content -LiteralPath $apiFile -Raw

function Get-Capture {
    param([string] $Text, [string] $Pattern)
    $match = [regex]::Match($Text, $Pattern)
    if ($match.Success) { return $match.Groups[1].Value }
    return ''
}

# public static string APIProductionBaseURL = "https://...";
$prodBase = Get-Capture $source 'APIProductionBaseURL\s*=\s*"([^"]*)"'
$devBase  = Get-Capture $source 'APIDevelopmentBaseURL\s*=\s*"([^"]*)"'
# ... APIBaseURL + "api/public_hook/v1/artwork?key=<KEY>"
$apiKey   = Get-Capture $source '[?&]key=([^"&\s]+)'
# ... APIBaseURL + "oauth/token"
$loginRel = Get-Capture $source 'APILogin\s*=\s*APIBaseURL\s*\+\s*"([^"]*)"'
# Path only, key stripped -- the Rust side appends the key at request time.
$collRel  = Get-Capture $source 'APICollectionBase\s*=\s*APIBaseURL\s*\+\s*"([^"?]*)'

if ([string]::IsNullOrWhiteSpace($prodBase)) { Write-Warning 'APIProductionBaseURL not matched -- check API.cs by hand.' }
if ([string]::IsNullOrWhiteSpace($apiKey))   { Write-Warning 'API key not matched -- check API.cs by hand.' }

# Realtime endpoint (docs/game-logic.md section 9). Not a secret.
$socketUrl = 'https://i-am-puzzle.map-india.org'

# ---------------------------------------------------------------------------
# OAuth credentials.
#
# These are NOT in code: they are serialized on the LoginHandler component in the
# scene. The collection endpoint returns HTTP 500 without a bearer token, so the
# login step is required, not optional (docs/game-logic.md section 8.3).
# ---------------------------------------------------------------------------
$scenePath = Join-Path $UnityRoot 'Assets/Games/Sliding-Puzzle/Scenes/MAP_PuzzleScene_Portrait.unity'
$oauth = @{
    grant_type    = ''
    client_id     = ''
    client_secret = ''
    username      = ''
    password      = ''
    scope         = ''
}

if (Test-Path -LiteralPath $scenePath) {
    $sceneText = Get-Content -LiteralPath $scenePath -Raw
    $block = [regex]::Match($sceneText, '(?m)^\s*loginData:\s*\r?\n((?:\s{4}\w+:.*\r?\n)+)')
    if ($block.Success) {
        foreach ($line in $block.Groups[1].Value -split "`r?`n") {
            if ([string]::IsNullOrWhiteSpace($line)) { continue }
            $pair = $line.Trim() -split ':', 2
            $name = $pair[0].Trim()
            if ($oauth.ContainsKey($name)) { $oauth[$name] = $pair[1].Trim() }
        }
    }
    else {
        Write-Warning 'loginData block not found in the portrait scene.'
    }
}
else {
    Write-Warning "Scene not found, so OAuth credentials were not extracted: $scenePath"
}

# dotenvy stops parsing at the first unquoted space, which silently dropped
# MAP_OAUTH_SCOPE ("read-artwork read-department") and every line after it. Quote
# any value that is not a bare token.
function Format-EnvValue([string] $Value) {
    if ([string]::IsNullOrEmpty($Value)) { return '' }
    if ($Value -match '[\s"#'']') {
        return '"' + ($Value -replace '\\', '\\\\' -replace '"', '\"') + '"'
    }
    return $Value
}

$lines = @(
    '# GENERATED by scripts/extract-api-config.ps1 -- DO NOT COMMIT.'
    '# Read only by the Tauri Rust side; never exposed to the renderer.'
    '# The key and client_secret extracted from the Unity repo are in git history'
    '# and MUST be rotated.'
    ''
    "MAP_API_BASE_URL=$(Format-EnvValue $prodBase)"
    "MAP_API_BASE_URL_DEV=$(Format-EnvValue $devBase)"
    "MAP_API_KEY=$(Format-EnvValue $apiKey)"
    "MAP_API_LOGIN_PATH=$(Format-EnvValue $loginRel)"
    "MAP_API_COLLECTION_PATH=$(Format-EnvValue $collRel)"
    "MAP_SOCKET_URL=$(Format-EnvValue $socketUrl)"
    ''
    '# OAuth2 (client_credentials). The collection endpoint 500s without a bearer token.'
    "MAP_OAUTH_GRANT_TYPE=$(Format-EnvValue $oauth['grant_type'])"
    "MAP_OAUTH_CLIENT_ID=$(Format-EnvValue $oauth['client_id'])"
    "MAP_OAUTH_CLIENT_SECRET=$(Format-EnvValue $oauth['client_secret'])"
    "MAP_OAUTH_USERNAME=$(Format-EnvValue $oauth['username'])"
    "MAP_OAUTH_PASSWORD=$(Format-EnvValue $oauth['password'])"
    "MAP_OAUTH_SCOPE=$(Format-EnvValue $oauth['scope'])"
)

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutFile) | Out-Null
$lines | Set-Content -LiteralPath $OutFile -Encoding utf8

# Masked report only.
Write-Host ''
Write-Host "Wrote $OutFile"
foreach ($pair in @(
    @{ Name = 'MAP_API_BASE_URL';        Value = $prodBase;  Secret = $true  }
    @{ Name = 'MAP_API_BASE_URL_DEV';    Value = $devBase;   Secret = $true  }
    @{ Name = 'MAP_API_KEY';             Value = $apiKey;    Secret = $true  }
    @{ Name = 'MAP_API_LOGIN_PATH';      Value = $loginRel;  Secret = $false }
    @{ Name = 'MAP_API_COLLECTION_PATH'; Value = $collRel;   Secret = $false }
    @{ Name = 'MAP_SOCKET_URL';          Value = $socketUrl; Secret = $false }
    @{ Name = 'MAP_OAUTH_GRANT_TYPE';    Value = $oauth['grant_type'];    Secret = $false }
    @{ Name = 'MAP_OAUTH_CLIENT_ID';     Value = $oauth['client_id'];     Secret = $true  }
    @{ Name = 'MAP_OAUTH_CLIENT_SECRET'; Value = $oauth['client_secret']; Secret = $true  }
    @{ Name = 'MAP_OAUTH_SCOPE';         Value = $oauth['scope'];         Secret = $false }
)) {
    if ([string]::IsNullOrWhiteSpace($pair.Value)) {
        Write-Host ("  {0,-24} MISSING" -f $pair.Name) -ForegroundColor Yellow
    }
    elseif ($pair.Secret) {
        Write-Host ("  {0,-24} set ({1} chars)" -f $pair.Name, $pair.Value.Length)
    }
    else {
        Write-Host ("  {0,-24} {1}" -f $pair.Name, $pair.Value)
    }
}

Write-Host ''
Write-Host 'ACTION REQUIRED: rotate MAP_API_KEY server-side. It is committed in the Unity repo history.' -ForegroundColor Red
Write-Host 'OAuth login credentials are serialized on the LoginHandler component in the Unity scene,' -ForegroundColor Yellow
Write-Host 'not in code. Add MAP_OAUTH_* values by hand if the port needs the login step.' -ForegroundColor Yellow
